### ISSUE TITLE
autocompletion / nettoyage des url

### ISSUE THREAD

**Issue by alexisju** [dimtion/Shaarlier#1]
Bonjour,
D'abord bravo pour cette app! Un vrai soulagement après des années d'utilisation de l'app Android Shaarli!

Je rencontre cependant deux petits soucis: l'autocompletion ne fonctionne pas et les attributs de tracking des url ne sont pas enlevés au moment d'enregistrer un nouveau lien.

Cela étant, j'utilise le fork communautaire de Shaarli (https://github.com/shaarli/Shaarli), ces problèmes sont peut-être lié à ça?

**Comment by dimtion** [comment]
Merci, pour le commentaire :).
Oui, l'autocompletion lors de la modification de la description et du titre ne fonctionnent pas pour le moment, et celui des tags n'est pas très fiable j'avais remarqué ce bug je le corrigerai dès la prochaine mise à jour. 

Pour les attributs d'url, merci de relever le bug, je pense que cela vient du fait que lors du post, l'app passe pas par le premier formulaire d'ajout. Je vais corriger cela.

**Comment by dimtion** [comment]
Normalement ces bugs sont corrigés dans la dernière version qui vient (à l'instant) d'être publiée. Merci encore pour le ticket.

**Comment by dimtion** [comment]
Bon apparemment j'étais sur une ancienne version de shaarli (plus de 30 jours) et ma méthode pour accéder aux tags a changé. Le bug n'est donc pas résolu.  
 Voir : https://github.com/dimtion/Shaarlier/issues/4
