### ISSUE TITLE
Has not been updated in Aptoide

### ISSUE THREAD

**Issue by NerosTie** [dimtion/Shaarlier#13]
Small issue here.
In Aptoide, it's still the version 1.2.3. No update to 1.2.4.

Plus, the signature for the app in Aptoide and in F-Droid are different. 
Is it possible to have the same signature for both?

Thanks.

**Comment by dimtion** [comment]
Yeah, sorry I forgot Aptoide, should be up to date by now (or very soon).

And I'm sorry, I cannot use the same signing key on f-droid for the only reason that I do not sign the app on F-droid. See : https://f-droid.org/wiki/page/FAQ_-_App_Developers#What_about_signing.3F

So I try my best to use the same key on the other stores.
