### ISSUE TITLE
define expected html structure (a.k.a. API) ?

### ISSUE THREAD

**Issue by mro** [dimtion/Shaarlier#15]
Hi @dimtion,

I recently published on iOS something very similar to what you did for Android. One of the problems I had was the missing API or how to parse the html and find the relevant data.

Do you think we should agree on a mechanism to parse the html so we consider the same shaarli templates valid and can give hints or even a testbed to template creators?

See https://github.com/mro/ShaarliOS/issues/1, does that make sense to you?

Cheers,
    @mro

P.S.: I'm curious how your share service looks like, can you add some screenshots to the README.md?
P.P.S.: stupid me, I found the screenshots in Google Play store.

**Comment by dimtion** [comment]
You are right I'm not using any specific API to publish links on Shaarli. As you [noted](https://github.com/dimtion/Shaarlier/commit/e55b150770b67561d0e07c8b1d5ab88b4f1ce52b#commitcomment-12407612) I parse the html to retrieve tokens and the relevant data. This means that if Shaarli structure change, the app will no longer work.  
When building the app I [asked](https://github.com/shaarli/Shaarli/issues/113) if it would be possible to create a REST API, for various reasons it was not accepted. Perhaps if we come up with more and better pleas than "I want an API for my app" we would have a

**Comment by dimtion** [comment]
You are right I'm not using any specific API to publish links on Shaarli. As you [noted](https://github.com/dimtion/Shaarlier/commit/e55b150770b67561d0e07c8b1d5ab88b4f1ce52b#commitcomment-12407612) I parse the html. This means that if Shaarli's structure changes, the app will no longer work. But, I only parse the html to retrieve tokens and check if the user is logged in (which is not optimal), and only the latter is template dependent. Every other requests are POST requests with the right parameters.

Sorry if my understanding of your code is a bit off (not an objective-C developer), but about https://github.com/mro/ShaarliOS/issues/1 it looks like your template is too specific : you are looking for element ids, you should be looking for the `name=""` tag which should not change between templates. 

When building the app I [asked](https://github.com/shaarli/Shaarli/issues/113) if it would be possible to create a REST API, for various reasons it was not accepted. Perhaps if we come up with more and better pleas we would have a better chance. Another problem with only using a bright new api would be the hundred of unsupported Shaarlis. By chance today with little duplicated code, the html parsing method support almost every Shaarli.  
[Another aborted discussion about an API](https://github.com/shaarli/Shaarli/issues/16)

Thanks for the attention given. I hope I helped you.

**Comment by mro** [comment]
other than form field ids (using them is https://github.com/mro/ShaarliOS/issues/3 and has to be changed), I look for the title or name of the whole shaarli instance via id. But I made that optional, so if it's missing the app will continue working flawlessly.

**Comment by mro** [comment]
@dimtion how do you locate error messages?

**Comment by dimtion** [comment]
I'm sorry, which error messages ? Errors sent by Shaarli ?

**Comment by mro** [comment]
Yes, e.g. wrong password or ip bans.

**Comment by mro** [comment]
would you mind having a look at https://github.com/shaarli/Shaarli/issues/16#issuecomment-137886509 - there's a strange issue with login and I wonder if you've seen it before.

The post-a-link flow can be seen here: https://github.com/mro/phptestdemo/blob/d0b6e568df43641ebe4dd5f079104d6410667109/scripts/test-post.sh#L29

[Update: solved meanwhile]

**Comment by mro** [comment]
continue at https://github.com/mro/ShaarliOS/issues/1

**Comment by mro** [comment]
Hi @dimtion what do you think about https://github.com/shaarli/Shaarli/pull/357 ?

Ho do you decide whether the link was really properly added or not?

**Comment by dimtion** [comment]
Hi,
Actually, I don't, I only check that each the server response is 200. 

The reason why I did that is because it is very simple. Also according to to Shaarli's source code, unless there is a server bug or a connection bug the link should very likely be posted.

But I follow you up on this pull request, it would be optimal to know for sure if the link has been posted.

**Comment by mro** [comment]
have you seen https://github.com/shaarli/Shaarli/pull/586 – what do you think about that?

**Comment by dimtion** [comment]
Thanks for the notification, this PR is great news.

However, I don't have statistics, but I  don't think many people update their Shaarli regularly, so jumping on this API and discarding back-compatibility would be a very bad move.

**Comment by mro** [comment]
> discarding back-compatibility would be a very bad move

indeed. I see
- a failing build the author doesn't even mention, let alone care about,
- increased code complexity (on our side),
- >800 LOC of immature code with zero tests,
- no API acceptance tests,
- no API documentation (which I would happily trade for acceptance tests),
- no clear security considerations, e.g. about brute force protection,

so I'm not enthusiastic about it.
