### ISSUE TITLE
Unable to shaare from FlymeOS default browser

### ISSUE THREAD

**Issue by ArthurHoaro** [dimtion/Shaarlier#19]
In the default browser of FlymeOS (Meizu branded Android), the Shaarlier icon isn't available when clicking on share. It's available on Plume for Twitter or Relay for Reddit though. 

![](http://imgur.com/wGT7AUM.png)

![](http://imgur.com/Aa6VyHU.png)

Android 5.1

**Comment by dimtion** [comment]
It might be coming from the format in which the browser send the data. Shaarlier only accepts "text/plain"  intents.

Are you using the default OwnCloud application ? Maybe I can find the answer in its source code.

**Comment by ArthurHoaro** [comment]
Yes I am. Although it says Nothing to send if I try to share something there. 

K9-mail might be a better help. Let me know if you want me to try something out.

**Comment by dimtion** [comment]
Do you have a way to know which mime type your browser uses ? I'm having a hard time installing FlymeOS...

**Comment by ArthurHoaro** [comment]
I don't know. I'll run a few tests to see if I can help.

**Comment by ArthurHoaro** [comment]
So, I made some tests. My simple app received `plain/text`, but is only available if it has this:

``` xml
<intent-filter>
    <action android:name="android.intent.action.SEND" />
    <category android:name="android.intent.category.DEFAULT" />
    <data android:mimeType="*/*" />
</intent-filter>
```

My guess is that they're doing [this](http://developer.android.com/training/sharing/send.html#send-binary-content):

> You can use a MIME type of "*/*", but this will only match activities that are able to handle generic data streams.

So, 2 possibilities:
- wontfix
- accept all mimetypes and only handle `text/plain` in your activity.

It's up to you.

**Comment by dimtion** [comment]
As @di72nn has said in #23 it is technically possible to handle more mimetypes optionally. But I am not very found of adding another option in the menu to handle this specific case.

What do you think of using the new checkbox created in #23 perhaps by renaming it in something more vague like "Handle more link types" ? In which case, most users won't be bothered by Shaarlier in all their unrelated share intents, and the few who have a problem can check this option.

I'm afraid that even #23 makes the UI a bit bulky.

**Comment by ArthurHoaro** [comment]
I don't think it's gonna work, because as I said, the minimal app I made actually receive `text/plain`, but only if I'm « listening » to `mimeType="*/*"`. This issue is very minor, and marginal, I don't think you should worry too much about it.

**Comment by ArthurHoaro** [comment]
This bug no longer exists with FlymeOS 5.
