### ISSUE TITLE
Comptabilité avec le plugin shaarli2twiiter

### ISSUE THREAD

**Issue by ebugnet** [dimtion/Shaarlier#26]
Bonjour,
Au cas ou, ça serait super si cette app pouvait être compatible avec le plugin https://github.com/ArthurHoaro/shaarli2twitter et permettre de choisir si un lien doit aussi être poussé sur twitter.
Merci
Éric

**Comment by angristan** [comment]
J'approuve, je pensais que ça se faisait par défaut.

**Comment by ebugnet** [comment]
Merci !

**Comment by dimtion** [comment]
Je viens de pousser un commit pour corriger ce problème.

Pour faire fonctionner le plugin vous devrez cocher dans les réglages l'option "Twitter" puisque je n'ai pas trouvé de moyen simple pour détecter le plugin.

Dites-le moi si vous voulez bien que je vous envoie une version alpha pour que vous puissiez tester avant que je déploie aux autres utilisateurs.

**Comment by angristan** [comment]
Je veux bien tester !

**Comment by ebugnet** [comment]
Moi aussi, merci !
Éric

**Comment by dimtion** [comment]
Désolé du retard, je viens de publier cette alpha à l'instant, si vous avez 5 minutes pour la tester n'hésitez pas : https://github.com/dimtion/Shaarlier/releases/tag/v1.4.0-alpha

**Comment by angristan** [comment]
Parfait, ça fonctionne !

**Comment by ArthurHoaro** [comment]
Merci pour l'ajout. Idéalement, il faudrait décocher et désactiver la case tweet si la case Private est activée.

**Comment by angristan** [comment]
Hey, ça serait possible d'ajouter également un bouton pour [Shaarli2Mastodon ](https://github.com/kalvn/shaarli2mastodon) ? :D C'est basé sur Shaarli2Twitter, donc je suppose que ça doit être presque pareil en termes d'implémentation. Je serais presque tenté de faire une PR en me basant sur ton commit mais je connais pas assez bien Java haha.

**Comment by poVoq** [comment]
Yeah Mastodon support would be also cool.

**Comment by dimtion** [comment]
Pourriez-vous ouvrir une autre issue pour l'intégration avec Shaarli2Mastodon ?

Il faudra que j'en profite pour simplifier l'intégration des différents plugins, à voir avec la nouvelle API Shaarli

**Comment by angristan** [comment]
C'est fait : https://github.com/dimtion/Shaarlier/issues/34
