### ISSUE TITLE
Show bookmark's data if it was saved before

### ISSUE THREAD

**Issue by bes1967** [dimtion/Shaarlier#28]
If your bookmark database is quite large it's hard to remember had you already stored concrete url in it or not. While storing bookmark using bookmarklet if url was stored previously you can see all the data entered for it - title, description and tags. It'll be nice to have same functionality in this application.

**Comment by dimtion** [comment]
This should be fixed in the latest release: https://github.com/dimtion/Shaarlier/releases/tag/v1.5.0

Please let me know if you have any issue.
