### ISSUE TITLE
Make add-link interface scrollable

### ISSUE THREAD

**Issue by dennisverspuij** [dimtion/Shaarlier#29]
Hello, thanks for the very useful app. Works great except for one problem, because the keyboard lays over the add-link interface it is virtually impossible to select tags from the autocomplete dropdown, I can only see and select the first item, any other tap closes the dropdown. Please make the interface scrollable and keep showing the dropdown when scrolling. TIA!

**Comment by dimtion** [comment]
Hi,
As a matter of fact, the UI *is* scrollable. But yes when the tags appears the UI doesn't increase in size. Normally the tags should appear above the field, not under the keyboard.

But indeed, it seems that the UI is buggy in some Android versions.

**Comment by dennisverspuij** [comment]
@dimtion Confirmed, the autocompletion dropdown now appears above the input field, I cannot reproduce my problem anymore, but I am sure I experienced it once. Will let know how to pupulate the fields if I reencounter the problem. But even then I guess it must be hard to resolve with all different screen and keyboard sizes. It migth be an idea to just always add extra height to the UI so it's always scrollable?

**Comment by dimtion** [comment]
I've planned to revamp the posting interface for the next release, this will be fixed. :)

**Comment by cal101** [comment]
Can some of this help?
https://stackoverflow.com/questions/16493017/close-keyboard-when-scrolling-in-dropdown-on-autocompletetextview-in-android

**Comment by dimtion** [comment]
In the last set of patches I'ved pushed, I've revamped the sharing interface which should fix this issue. Please let me know if you want me to build an alpha release for you to test.

**Comment by dimtion** [comment]
This should be fixed in the latest release: https://github.com/dimtion/Shaarlier/releases/tag/v1.5.0

Please let me know if you have any issue.

**Comment by dennisverspuij** [comment]
Works great thanks!
