### ISSUE TITLE
Add the apk to F-droid and/or Aptoide

### ISSUE THREAD

**Issue by NerosTie** [dimtion/Shaarlier#3]
Some people, like me, don't use the Google Play Store.
It could be great to have the apk somewhere and, better, in stores like F-droid and Aptoide for easy updates.

(great app for Shaarli, I like it! :+1: )

**Comment by dimtion** [comment]
You can download the last apk from this page whereas it is not the lastest update : 
https://github.com/dimtion/Shaarlier/releases

I will probably put the next version on the stores you suggested for easier updates. I'll notify you here when it's done.

**Comment by NerosTie** [comment]
Great, thank you :)

**Comment by alexisju** [comment]
F-Droid :+1:

**Comment by dimtion** [comment]
I just published the latest version, it is currently available on the [releases tab](https://github.com/dimtion/Shaarlier/releases) and on the [Aptoide store](http://dimtion.store.aptoide.com/app/market/com.dimtion.shaarlier/8/8917968/Shaarlier). Sorry for the ugly presentation page. 

For F-Droid it will take a little longer.

**Comment by NerosTie** [comment]
Updated from the Aptoide store. Worked perfectly!
