### ISSUE TITLE
Unable to select account when shaaring a link

### ISSUE THREAD

**Issue by mathong** [dimtion/Shaarlier#30]
Hi,

My Shaarlier is connected to 2 Shaarli instances. When I'm sharing a link (or a note), I can't select the target account. It seems that account names are in some kind of nested dropdown lists:
![test](https://user-images.githubusercontent.com/12710607/29119621-2603163a-7d07-11e7-8c42-4c6112c9bc31.jpg)
I noticed that you can hack this issue by long pressing the first account dropdown list and then swipe to select.

Could you please fix it?
Thanks

Shaarlier version: 1.3.0
Shaarli version: 0.9.0
OS: Android 7.0

**Comment by husimo** [comment]
Hello. Same problem with android 7.1. Thank you

**Comment by uriel1998** [comment]
Likewise. This is a really important functionality for me, and I'd love to see it.

**Comment by TheNomad11** [comment]
Same here with Android 8.1

**Comment by dimtion** [comment]
Hello,
I have just pushed a set of patches that should fix this issue. If you would like to test the patch, please let me know, I'll build an alpha release for you.

**Comment by dimtion** [comment]
This should be fixed in the latest release: https://github.com/dimtion/Shaarlier/releases/tag/v1.5.0

Please let me know if you have any issue.
