### ISSUE TITLE
Impossible to connect my Shaarli when included in a wordpress template

### ISSUE THREAD

**Issue by opitux** [dimtion/Shaarlier#31]
Hello,

Shaarlier can not connect to my shaarli when it is included in a wordpress (header/footer) template.

I duplicated an original Shaarli in another folder, connected with my original datastore.php to Shaarlier it but I don't think this is the right way ;)

By the way, many thanks for Shaarlier :)

**Comment by dimtion** [comment]
Do you have a link for me to investigate, the problem might be in the parsing of the login page, but without any example it is hard to pin point the problem.

**Comment by opitux** [comment]
Hello :)

**Comment by opitux** [comment]
Hello :)

I removed the wordpress integration for the shaarli I use with shaarlier. I can do it again for test. What do you need exactly ? Wordpress integration and corresponding id/password ?

**Comment by dimtion** [comment]
Hello Opitux, 

Sorry for the very late response (1 year later).

I've pushed a new release of the application, do you still encounter the issue? If so can you please me help me pin-point the issue with the following information:

* Version of Shaarli
* What template are you using (Name and version)
* When exactly does you encounter the issue: When registering your account, when sharing a link?

With that in mind I'll try to reproduce the issue. Note that once #37 is closed, this very issue should disappear.

Thanks for your time
