### ISSUE TITLE
Compatibilité Shaarli2Mastodon

### ISSUE THREAD

**Issue by angristan** [dimtion/Shaarlier#34]
Issue pour demander l'ajout de la compatibilité avec https://github.com/kalvn/shaarli2mastodon.

Merci !

**Comment by MagicFab** [comment]
J'ajoute Mastodon pour les mots clés de recherche - le moteur Github ne trouve pas ce rapport, sinon.

**Comment by Nono-m0le** [comment]
Un moyen de participer pour avancer sur cet 'issue'?
