### ISSUE TITLE
Failed to share

### ISSUE THREAD

**Issue by spectreman51** [dimtion/Shaarlier#36]
Bonjour, impossible de partager sur 3 smartphones différents. Toujours le même message: failed to share.. Merci

**Comment by dimtion** [comment]
Bonjour,

Peux-tu me donner plus de détails sur ton installation ? Quelle version de Shaarli, quelle version de Shaalier, quel version Android ?

Un conseil que je peux te donner c'est dans les options d'optimisation de batterie sur l'application, cela permet parfois de mieux faire fonctionner les requêtes réseau.

**Comment by spectreman51** [comment]
BonjourMerci pour ta réponse. J'utilise shaarli en version master v0. 10.2 hébergé sur pages perso free, shaarlier dans la dernière version. J'ai le problème sur 2 téléphones dont le plus récent en Android 8.1.0 et une tablette dans une version plus ancienne. Je soupçonne l'hébergement chez free.  Je vais essayer d'installation shaarli sur un raspberry. Chose étrange :aucun partage possible sur Android sauf avec l'application Wikipedia.Je fais le test sur rpi et je te tiens au courant. Merci. Envoyé depuis mon téléphone Orange-------- Message original --------Objet : Re: [dimtion/Shaarlier] Failed to share (#36)De : Loïc Carr À : dimtion/Shaarlier Cc : spectreman51 ,Author Bonjour,
Peux-tu me donner plus de détails sur ton installation ? Quelle version de Shaarli, quelle version de Shaalier, quel version Android ?
Un conseil que je peux te donner c'est dans les options d'optimisation de batterie sur l'application, cela permet parfois de mieux faire fonctionner les requêtes réseau.

**Comment by jerometerrier** [comment]
Did you solve this issue?
I have the same problem.
thx

**Comment by vjrj** [comment]
I have to retry several times til it works. It  seems to me that has a small timeout calling the API because fails very fast.

I'm  using the last version 1.6.0

**Comment by dimtion** [comment]
Hi @spectreman51 @jerometerrier,

I've published [version 1.6.1](https://github.com/dimtion/Shaarlier/releases/tag/v1.6.1) which fixes a bug on Android 9, you might have a look. Unfortunately without more information I have a hard time pin-pointing the issue you are encountering.

Please let me know if you have more information about this bug.
