### ISSUE TITLE
No autocompletion on tags

### ISSUE THREAD

**Issue by NerosTie** [dimtion/Shaarlier#4]
In releases notes you talk about autocompletion on tags but there is no such thing when I try it.
(version 1.0.3)

**Comment by dimtion** [comment]
Which fork of shaarli are you using ? Did the "Test settings" button displayed a success message ?

**Comment by NerosTie** [comment]
I'm using the community fork ( https://github.com/shaarli/Shaarli/ ).
The "Try the settings" button says "the settings are fine"

**Comment by dimtion** [comment]
Which version of android are you running ?

**Comment by NerosTie** [comment]
![screenshot_2015-04-04-23-48-34](https://cloud.githubusercontent.com/assets/4572452/6994766/2f8475c2-db25-11e4-80c6-64e1f852a821.png)

**Comment by dimtion** [comment]
Sorry, I went to your Shaarli to find the problem.
I don't know if it is because of your theme or else, but to retrieve the auto-complete tags, the app do a get request to ?ws=tags&term=+
In your case your Shaarli (and probably some others) only return the frontpage on that request. Can you have a look on how your Shaarli handle tags ? Maybe the parameters have changed...

**Comment by NerosTie** [comment]
I switched-back to the default theme and the issue is still here.
I don't know where to look to knwo how my shaarli handles tags, can you explain?

**Comment by dimtion** [comment]
I will take as example Firefox but it should be the same for any other browser.
So choose a random link, login into your Shaarli and create the link `Add link->Add link`  you should now be on the page for editing links) : `?post=`
Now open the network tools `ctrl+maj+q`, if necessary reload the page and add some random text in the tag textEdit. Can you tell me what requests the browser does ?

Thanks in advance.

**Comment by NerosTie** [comment]
Well, nothing related with tags but it uses awesomplete.js
![shaarli_tags](https://cloud.githubusercontent.com/assets/4572452/6994930/23a7384c-db2b-11e4-973e-02c5f3435521.png)

( 2 tags was in the tag edit)

**Comment by dimtion** [comment]
If you add random tags in the tag field does it make any other http
requests ?

**Comment by NerosTie** [comment]
No, nothing happen.
What Shaarli are you using?

**Comment by dimtion** [comment]
I'm using the community version (same as yours) but I think you are right : it is the use of awesomplete library which breaks compatibility. 

I maybe try to find a turn around but, I think the better way is to open an issue on this project : https://github.com/kalvn/Shaarli-Material

The thing is, I cannot make an different api for every version of shaarly, so fork developers should try not to break any api compatibility when adding new features.

**Comment by NerosTie** [comment]
You are right, it's from the theme. I will open an issue. Thank you!

**Comment by NerosTie** [comment]
In fact, I'm not sure it's from the Material theme.

awesomplete.js is in the last release of the community shaarli.
Look: https://github.com/shaarli/Shaarli/tree/master/inc

If both of us have the same shaarli, you should have awesomplete too.

**Comment by dimtion** [comment]
Ok, sorry if I was a bit too fast and was not up to date. I'll fix that
tomorrow. I think you should close the issue on the theme repo. My bad.

**Comment by NerosTie** [comment]
No problem :wink:

**Comment by dimtion** [comment]
Would you mind if I ask to you to try and test this release : https://github.com/dimtion/Shaarlier/releases/tag/v1.0.4 ?
It works on my device.
Thanks in advance.

**Comment by NerosTie** [comment]
It works!
Great job! :smile:

**Comment by dimtion** [comment]
My pleasure :)
