### ISSUE TITLE
Search for substrings in tags

### ISSUE THREAD

**Issue by immanuelfodor** [dimtion/Shaarlier#41]
I got the idea in #20 to add enhancements to Shaarlier, one of these could be searching for substrings in tags (not only prefixes). When you have so many tags, you don't remember the exact tag name, just a fragment, e.g., **ops** for operations, dev**ops**, devsec**ops**, cr**ops**123. The current search algorithm expects you to know the prefix, it would be great to list all matching tags with bold textual representation on the matched fragment.

**Comment by dimtion** [comment]
That would be a nice to add. I'm not adding this on the roadmap yet since there are more urgent matters.

Please note that this could be a beginner task for anyone to contribute!

**Comment by dimtion** [comment]
As a notice, in the latest commit 4668d9f18374f2bc4bfdef525f257840f50603c2 I've added a fuzzy search on the tag list. I'm still in the process of tuning the sensitivity to avoid too many unwanted results, but this will surely go to the next release.

**Comment by immanuelfodor** [comment]
Wow, this will be awesome!

**Comment by dimtion** [comment]
The update is live. I'm closing this issue.

https://github.com/dimtion/Shaarlier/releases/tag/v1.8.0
