### ISSUE TITLE
Wrong url to my shaarli

### ISSUE THREAD

**Issue by arnauldb** [dimtion/Shaarlier#45]
Hello,
I tried to input my shaarli url with:
https://xxxxx.com/shaarli and shaarli.xxxx.com but none of them work. I can of course access my shaarli instance with https://xxxxx.com/shaarli
Which url do I have to use in Shaarlier?
Thank you.

**Comment by dimtion** [comment]
Hi @arnauldb,


Normally if you can access your Shaarli from both url, you can use any of them in Shaarlier. Make sure that the API rest is enabled in your settings and that `mod_rewrite` is enabled on your Apache and correctly configured, see [Shaarli documentation](https://shaarli.readthedocs.io/en/doc-rework-setup/Server-configuration/#examples)

Let me know if you need any more information,

**Comment by dimtion** [comment]
Hi @arnauldb,

Another possibility is a missing piece in you Apache configuration: have you correctly added the following to your virtualhost?
```
   <Directory /var/www/shaarli.mydomain.org/>
        # Required for .htaccess support
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
```

**Comment by mro** [comment]
> access my shaarli instance with https://xxxxx.com/shaarli

I cannot, but rather see a sedo-parking-page. May this be the issue?

**Comment by dimtion** [comment]
@mro Same, I guess this was probably an example URL @arnauldb gave. 

Anyway I'm closing this.
