### ISSUE TITLE
No share option on MIUI default web browser

### ISSUE THREAD

**Issue by NerosTie** [dimtion/Shaarlier#5]
Using the default web browser from the custom Android rom called "MIUI", there is no share option for shaarlier.

**Comment by dimtion** [comment]
Mmm, strange, I don't quite understand why this particular app doesn't handle a the sharing button. Do you have the name of the browser ? I can only find one called Charming Browser, but it wasn't updated since 2010. 
Do you know if you browser use a custom android share button or the default android one  ?

**Comment by NerosTie** [comment]
Well, the name is "browser" and it's not helping because I can't find an apk somewhere.
I can send you a backup version of mine but it's not a great thing to do...

I don't know if default apps use a custom share button or not... but other apps I use are in (like skype, kde connect, ...), so Shaarlier shoud work too.

**Comment by dimtion** [comment]
Could you give me some screenshots of the browser's share menu ?

**Comment by NerosTie** [comment]
![screenshot_2015-05-11-17-06-45](https://cloud.githubusercontent.com/assets/4572452/7567963/6d177e14-f800-11e4-8413-f9f14dd93d07.png)
![screenshot_2015-05-11-17-06-51](https://cloud.githubusercontent.com/assets/4572452/7567964/6d1ac100-f800-11e4-9f44-3552c33303fc.png)

Here they are! I'm using the last version (1.1.0b).

**Comment by dimtion** [comment]
Sorry for being late.  

Unfortunately I think I have little control over this. They are indeed using a custom share dialog and the only way (I found) to be on the list would be to ask them directly. But being so little, I'm not very optimistic about them adding us...  

The temporary solution I would propose is a bad one : try another browser... 

In the mean time I'll have a look at their developer documents to see if I missed something.

**Comment by NerosTie** [comment]
Hm, I don't think Kde Connect ask them for that. Maybe something is missing somewhere...

But, it's ok, now I'm using Chrome which is better :)
