### ISSUE TITLE
Shaarlier displays "wrong" message

### ISSUE THREAD

**Issue by Arrappathor** [dimtion/Shaarlier#50]
Hi, 

I use the shaarlier v1.8.0.
Today I upgraded my Shaarli-instance to v0.12 and then had to change my login-credentials to REST-API secret.
When I now share links to my shaarli, the message "Failed to share" is displayed.
Nevertheless: the links are stored to my shaarli!
Any hint? Any other information needed?
Besides this: a very fine app, I use it for three years now! 
Thank you!

Arrappathor

**Comment by trial-n-error** [comment]
Problem occurs on my end as well with shaarlier 1.8.0 and shaarli 0.12.0, leading to the following notification:

"
Failed to share Search: ...
Press to try again
"

Once I press, it flashed "Your link has been shared".

It seems the link was already shared before even when the notification says different.

**Comment by dimtion** [comment]
Hi,

Thank you for reporting this issue, this is an issue with Shaarli, I just posted a PR that should fix it https://github.com/shaarli/Shaarli/pull/1616

**Comment by Arrappathor** [comment]
Solved with update to shaarli 0.12.1
Thank you very much!
